name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Setup Fyne dependencies
      run: | 
        go get fyne.io/fyne/v2@latest
        go install fyne.io/fyne/v2/cmd/fyne@latest
        go get fyne.io/fyne/v2/internal/svg@v2.6.0

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
